---
title: "RChallange1"
author: "Erica Westerman"
date: "September 15, 2015"
output:
  html_document:
    toc: true
    number_sections: true
    theme: cerulean
    highlight: espresso
    fig_width: 8
    fig_height: 8
    fig_caption: yes
---

#Load the data
## second header!
```{r load_data,  echo=FALSE}
counts_raw <- read.delim("data/counts-raw.txt.gz")
counts_norm <- read.delim("data/counts-norm.txt.gz")

```

# Data exploration
What's the distribution of authors in all articles of our data set?

```{r histogram, fig.cap="Figure 1: Authors", echo=FALSE}
hist(counts_raw$authorsCount, main = "Authors per paper", xlab = " # authors")

```

# Histogram two, Facebook
What is the number of facebook shares per article?

```{r histogram2, fig.cap="Figure 2: Facebook shares per article", echo=FALSE}
hist(counts_raw$facebookShareCount, main = "Facebook shares per article", xlab = " # shares")
```

The average number of Facebook share per paper in the data set is **`r 
mean(counts_raw$facebookShareCount)`**



```

